const MISSIONS = [
  ['감정과 공감', '주인공의 기분은 어땠을까요?'], ['감정과 공감', '주인공에게 어떤 말을 해주고 싶나요?'], ['감정과 공감', '이 책에서 가장 따뜻했던 장면은 무엇인가요?'], ['감정과 공감', '내가 공감한 인물은 누구인가요?'], ['감정과 공감', '읽고 난 뒤 내 기분은 어떤가요?'], ['감정과 공감', '등장인물의 마음이 바뀐 순간은 언제인가요?'],
  ['등장인물', '가장 기억에 남는 인물은 누구인가요?'], ['등장인물', '내가 주인공이라면 어떻게 했을까요?'], ['등장인물', '주인공의 장점 한 가지를 찾아보세요.'], ['등장인물', '등장인물 한 명을 친구에게 소개해 보세요.'], ['등장인물', '나와 가장 비슷한 인물은 누구인가요?'], ['등장인물', '인물에게 새로운 별명을 지어 주세요.'],
  ['장면과 문장', '가장 기억에 남는 장면은 무엇인가요?'], ['장면과 문장', '기억에 남는 문장을 적어 보세요.'], ['장면과 문장', '책 속 한 장면을 그림으로 표현한다면?'], ['장면과 문장', '이야기의 장소는 어떤 모습이었나요?'], ['장면과 문장', '제목을 다른 이름으로 바꾼다면?'], ['장면과 문장', '책의 분위기를 색깔로 표현한다면?'],
  ['추천과 평가', '친구에게 이 책을 추천한다면 어떤 말을 할까요?'], ['추천과 평가', '이 책에 별점을 준다면 몇 점인가요?'], ['추천과 평가', '이 책을 한 문장으로 소개해 보세요.'], ['추천과 평가', '누구에게 이 책을 추천하고 싶나요?'], ['추천과 평가', '이 책에서 배운 점은 무엇인가요?'], ['추천과 평가', '이 책을 읽기 전과 후에 달라진 생각은?'],
  ['상상과 이어쓰기', '결말을 바꾼다면 어떻게 바꾸고 싶나요?'], ['상상과 이어쓰기', '이야기의 다음 장면을 상상해 보세요.'], ['상상과 이어쓰기', '내가 책 속에 들어간다면 무엇을 할까요?'], ['상상과 이어쓰기', '이 책에 새로운 인물을 넣는다면?'], ['상상과 이어쓰기', '주인공에게 특별한 능력이 생긴다면?'], ['상상과 이어쓰기', '이 이야기를 영화로 만든다면 어떤 장면을 넣을까요?']
];
// Google Apps Script 웹 앱 URL을 넣으면 미션 답변 저장 순간 구글시트로 전송됩니다.
// 비워 두면 기존처럼 기기 안에만 저장됩니다.
const APPS_SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbyURR70AxJAAS3i8KzPgZgwLiyGVrPpYQj2DUpMSYcySYuQc594idzWwp6rU125nyG4aQ/exec';
const LEVELS = [
  { books: 0, name: '독서 준비생', icon: '🌱' }, { books: 5, name: '독서 첫걸음', icon: '🌱' }, { books: 10, name: '새싹 독서가', icon: '🌿' }, { books: 20, name: '책 탐험가', icon: '🌿' }, { books: 40, name: '꾸준한 독서가', icon: '🍃' }, { books: 60, name: '이야기 수집가', icon: '🌳' }, { books: 80, name: '독서 여행자', icon: '🌳' }, { books: 100, name: '책의 친구', icon: '🌳' }, { books: 130, name: '지식 탐험가', icon: '🌳' }, { books: 160, name: '독서 고수', icon: '📚' }, { books: 200, name: '책 마스터', icon: '📚' }
];
const KEY = 'read-step-data-v1';
const state = { view: 'home', authMode: 'create', lastMissionIndex: null, pendingBook: null, mission: null, rating: 0 };
let data = JSON.parse(localStorage.getItem(KEY) || 'null');

function save() { localStorage.setItem(KEY, JSON.stringify(data)); }
function syncRecordToSheet(record) {
  if (!APPS_SCRIPT_URL) return;
  const payload = {
    nickname: data.nickname,
    title: record.title,
    author: record.author,
    date: record.date,
    rating: record.rating,
    category: record.category,
    mission: record.mission,
    answer: record.answer,
    books: data.books,
    stickers: data.stickers
  };
  fetch(APPS_SCRIPT_URL, {
    method: 'POST',
    mode: 'no-cors',
    headers: { 'Content-Type': 'text/plain;charset=utf-8' },
    body: JSON.stringify(payload)
  }).catch(() => { /* 시트 전송 실패와 관계없이 기기 안의 기록은 유지합니다. */ });
}
function esc(value = '') { return String(value).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
function currentLevel() { let result = LEVELS[0]; LEVELS.forEach(level => { if (data.books >= level.books) result = level; }); return result; }
function nextLevel() { return LEVELS.find(level => level.books > data.books) || LEVELS[LEVELS.length - 1]; }
function monthBooks() { const month = new Date().toISOString().slice(0, 7); return data.records.filter(r => r.date.startsWith(month)).length; }
function progress() { const current = currentLevel(); const next = nextLevel(); if (current.books === next.books) return 100; return Math.min(100, ((data.books - current.books) / (next.books - current.books)) * 100); }
function pickMission() { let index; do { index = Math.floor(Math.random() * MISSIONS.length); } while (MISSIONS.length > 1 && index === state.lastMissionIndex); state.lastMissionIndex = index; return MISSIONS[index]; }
function stars(n) { return '★'.repeat(n) + '☆'.repeat(5 - n); }
function layout(content, active = 'home') { return `<div class="shell"><div class="container"><header class="topbar"><div class="brand"><span class="brand-mark">책</span><div>독서한걸음<small>${esc(data.nickname)}님의 독서 기록</small></div></div><div class="topbar-actions"><button class="ghost-button" data-action="logout">잠시 나가기</button></div></header><nav class="nav-tabs" aria-label="주요 메뉴"><button class="${active === 'home' ? 'active' : ''}" data-view="home">홈</button><button class="${active === 'record' ? 'active' : ''}" data-view="record">독서 기록</button><button class="${active === 'growth' ? 'active' : ''}" data-view="growth">성장 현황</button></nav>${content}</div></div>`; }
function home() { const level = currentLevel(); const next = nextLevel(); return layout(`<section class="hero"><div class="hero-copy"><p class="eyebrow">오늘의 독서 한 걸음</p><h1>읽은 책이<br>나의 성장이 돼요.</h1><p class="subtitle">책 한 권을 기록하면 오늘의 랜덤 미션이 나타나요.<br>생각을 남기고 스티커를 모아 보세요.</p><div class="button-row"><button class="primary-button" data-view="record">독서 기록하기</button><button class="secondary-button" data-view="growth">성장 현황 보기</button></div></div><div class="hero-visual"><div class="growth-tree">${level.icon}</div></div></section><section class="stats"><div class="stat"><div class="stat-label">이번 달 읽은 권 수</div><div class="stat-value">${monthBooks()}권</div><div class="stat-note">꾸준히 읽고 있어요</div></div><div class="stat"><div class="stat-label">총 읽은 책</div><div class="stat-value">${data.books}권</div><div class="stat-note">다음 목표 ${next.books}권</div></div><div class="stat"><div class="stat-label">총 스티커</div><div class="stat-value">${data.stickers}개</div><div class="stat-note">미션 완료 보상</div></div><div class="stat"><div class="stat-label">현재 업적</div><div class="stat-value">LV.${String(LEVELS.indexOf(level)).padStart(2, '0')}</div><div class="stat-note">${level.name}</div></div></section><section class="dashboard-grid"><div class="panel"><div class="panel-header"><div><p class="eyebrow">다음 목표</p><h2>${level.name}</h2></div><span class="badge">${data.books}권 읽음</span></div><div class="level-row"><div class="level-icon">${level.icon}</div><div class="level-copy"><div class="level-title">LV.${String(LEVELS.indexOf(level)).padStart(2, '0')} ${level.name}</div><div class="progress"><span style="width:${progress()}%"></span></div><div class="progress-note"><span>현재 ${data.books}권</span><span>${next.books === level.books ? '최고 레벨!' : `다음 ${next.books}권`}</span></div></div></div></div><div class="panel"><div class="panel-header"><div><p class="eyebrow">나의 약속</p><h2>한 권씩, 한 걸음씩</h2></div></div><p class="subtitle">오늘 읽은 책을 기록하고<br>새로운 질문을 만나 보세요.</p><button class="primary-button" data-view="record">기록 시작하기</button></div></section>`, 'home'); }
function recordForm() { state.rating = 0; return layout(`<section class="page-title"><div><p class="eyebrow">BOOK RECORD</p><h1>읽은 책을 기록해요.</h1><p class="subtitle">책 정보를 남기면 나에게 맞는 오늘의 미션이 나타나요.</p></div></section><form class="form-card" id="book-form"><div class="form-grid"><div class="field full"><label for="title">책 제목</label><input id="title" name="title" required placeholder="예: 마당을 나온 암탉" /></div><div class="field"><label for="author">저자</label><input id="author" name="author" required placeholder="예: 황선미" /></div><div class="field"><label for="date">읽은 날짜</label><input id="date" name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required /></div><div class="field full"><label>별점</label><div class="rating" role="radiogroup" aria-label="별점">${[1,2,3,4,5].map(n => `<button type="button" class="star" data-rating="${n}" aria-label="${n}점">★</button>`).join('')}</div></div></div><div class="button-row"><button class="primary-button" type="submit">다음: 랜덤 미션 보기</button><button class="secondary-button" type="button" data-view="home">취소</button></div></form>`, 'record'); }
function missionView() { if (!state.mission) state.mission = pickMission(); return layout(`<section class="page-title"><div><p class="eyebrow">TODAY'S RANDOM MISSION</p><h1>책을 읽고, 생각을 남겨요.</h1><p class="subtitle"><strong>${esc(state.pendingBook.title)}</strong>을(를) 읽고 다음 질문에 답해 보세요.</p></div></section><section class="mission-layout"><aside class="mission-quote"><div><span class="badge">${esc(state.mission[0])}</span><div class="big" style="margin-top:26px;">${esc(state.mission[1])}</div></div><button class="secondary-button" type="button" data-action="reroll">다른 미션 뽑기</button></aside><form class="form-card" id="mission-form"><div class="field"><label for="answer">나의 생각</label><textarea id="answer" required placeholder="책을 읽고 떠오른 생각을 자유롭게 적어 보세요."></textarea></div><p class="notice">답변을 저장하면 독서 기록이 완성되고 스티커 1개를 받을 수 있어요.</p><button class="primary-button" type="submit">답변 저장하고 스티커 받기</button></form></section>`, 'record'); }
function growth() { const level = currentLevel(); const next = nextLevel(); return layout(`<section class="page-title"><div><p class="eyebrow">MY READING GROWTH</p><h1>나의 성장 현황</h1><p class="subtitle">읽은 책과 미션 기록이 한곳에 차곡차곡 쌓여요.</p></div></section><section class="panel" style="margin-bottom:18px"><div class="level-row"><div class="level-icon">${level.icon}</div><div class="level-copy"><div class="level-title">LV.${String(LEVELS.indexOf(level)).padStart(2, '0')} ${level.name}</div><p class="subtitle" style="margin:6px 0 0">총 ${data.books}권 · 스티커 ${data.stickers}개</p><div class="progress"><span style="width:${progress()}%"></span></div><div class="progress-note"><span>현재 ${data.books}권</span><span>${next.books === level.books ? '최고 레벨 달성' : `다음 업적까지 ${Math.max(0, next.books - data.books)}권`}</span></div></div></div></section><section class="panel"><div class="panel-header"><div><p class="eyebrow">READING LOG</p><h2>나의 독서 기록</h2></div><span class="badge">총 ${data.records.length}권</span></div>${data.records.length ? `<div class="record-list">${data.records.slice().reverse().map(r => `<details class="record-item"><summary><div><strong>${esc(r.title)}</strong><span class="record-meta">${esc(r.author)} · ${esc(r.date)}</span></div><span class="record-rating">${stars(r.rating)}</span></summary><div style="padding-top:14px;color:var(--muted);line-height:1.6;font-size:14px"><strong style="color:var(--ink)">${esc(r.mission)}</strong><br>${esc(r.answer)}</div></details>`).join('')}</div>` : '<div class="empty">아직 기록한 책이 없어요. 첫 번째 책을 기록해 보세요.</div>'}</section>`, 'growth'); }
function auth() { return `<div class="auth-wrap"><div class="auth-card"><div class="brand"><span class="brand-mark">책</span><div>독서한걸음<small>읽고, 기록하고, 성장해요</small></div></div><p class="eyebrow">MY READING SPACE</p><h1>${state.authMode === 'create' ? '나만의 독서 기록을\n시작해 보세요.' : '독서한걸음\n불러오기'}</h1><p class="subtitle">실명 없이 닉네임으로 기록을 관리해요.<br>이 기기에 안전하게 저장됩니다.</p><div class="auth-toggle"><button class="${state.authMode === 'create' ? 'active' : ''}" data-action="auth-create">처음 시작하기</button><button class="${state.authMode === 'login' ? 'active' : ''}" data-action="auth-login">불러오기</button></div><form id="auth-form"><div class="field"><label for="nickname">닉네임</label><input id="nickname" required maxlength="16" placeholder="예: 책벌레" /></div><div class="field"><label for="pin">4자리 비밀번호</label><input id="pin" required inputmode="numeric" pattern="[0-9]{4}" maxlength="4" placeholder="숫자 4자리" /></div>${state.authMode === 'create' ? '<div class="field"><label for="pin-confirm">비밀번호 확인</label><input id="pin-confirm" required inputmode="numeric" pattern="[0-9]{4}" maxlength="4" placeholder="한 번 더 입력해 주세요" /></div>' : ''}<div id="auth-error" class="error" role="alert"></div><button class="primary-button" style="width:100%" type="submit">${state.authMode === 'create' ? '독서한걸음 기록하기' : '시작하기'}</button></form><p class="notice">닉네임과 비밀번호를 잊으면 이 기기의 기록을 불러오기 어려워요.</p></div></div>`; }
function success() { return `<div class="success"><div class="sticker-pop">⭐</div><p class="eyebrow">MISSION COMPLETE</p><h2>스티커 1개 획득!</h2><p class="subtitle">${esc(state.pendingBook.title)} 기록이 저장됐어요.<br>한 걸음 더 성장했어요.</p><div class="level-row" style="text-align:left;margin:22px 0"><div class="level-icon">${currentLevel().icon}</div><div class="level-copy"><div class="level-title">LV.${String(LEVELS.indexOf(currentLevel())).padStart(2, '0')} ${currentLevel().name}</div><div class="progress"><span style="width:${progress()}%"></span></div></div></div><div class="button-row" style="justify-content:center"><button class="primary-button" data-view="record">다음 책 기록하기</button><button class="secondary-button" data-view="growth">성장 현황 보기</button></div></div>`; }
function render() { if (!data) { document.querySelector('#app').innerHTML = auth(); return; } let html = state.view === 'home' ? home() : state.view === 'record' ? (state.mission ? missionView() : recordForm()) : state.view === 'growth' ? growth() : success(); document.querySelector('#app').innerHTML = html; }
document.addEventListener('click', e => { const view = e.target.closest('[data-view]')?.dataset.view; if (view) { state.view = view; state.pendingBook = null; state.mission = null; render(); return; } const action = e.target.closest('[data-action]')?.dataset.action; if (!action) return; if (action === 'auth-create') { state.authMode = 'create'; render(); } if (action === 'auth-login') { state.authMode = 'login'; render(); } if (action === 'logout') { data = null; state.view = 'home'; render(); } if (action === 'reroll') { state.mission = pickMission(); render(); } });
document.addEventListener('click', e => { const star = e.target.closest('[data-rating]'); if (!star) return; state.rating = Number(star.dataset.rating); document.querySelectorAll('.star').forEach((el, i) => el.classList.toggle('active', i < state.rating)); });
document.addEventListener('submit', e => { e.preventDefault(); if (e.target.id === 'auth-form') { const nickname = document.querySelector('#nickname').value.trim(); const pin = document.querySelector('#pin').value.trim(); const error = document.querySelector('#auth-error'); if (!/^\d{4}$/.test(pin)) { error.textContent = '비밀번호는 숫자 4자리로 입력해 주세요.'; return; } if (state.authMode === 'create') { const confirm = document.querySelector('#pin-confirm').value.trim(); if (pin !== confirm) { error.textContent = '비밀번호가 서로 다릅니다.'; return; } data = { nickname, pin, books: 0, stickers: 0, records: [] }; save(); state.view = 'home'; render(); } else { const saved = JSON.parse(localStorage.getItem(KEY) || 'null'); if (!saved || saved.nickname !== nickname || saved.pin !== pin) { error.textContent = '닉네임 또는 비밀번호를 확인해 주세요.'; return; } data = saved; state.view = 'home'; render(); } } if (e.target.id === 'book-form') { const form = new FormData(e.target); state.pendingBook = { title: form.get('title').trim(), author: form.get('author').trim(), date: form.get('date'), rating: state.rating || 0 }; state.mission = pickMission(); render(); } if (e.target.id === 'mission-form') { const answer = document.querySelector('#answer').value.trim(); if (!answer) return; const record = { ...state.pendingBook, mission: state.mission[1], category: state.mission[0], answer, createdAt: new Date().toISOString() }; data.records.push(record); data.books += 1; data.stickers += 1; save(); syncRecordToSheet(record); state.view = 'success'; render(); } });
render();
